- screwdriver/screwdriver.go
We fixed escape processing because it failed to escape meta characters.
Use `strconv.Quote`
> Fix: escape meta character in yaml

- .gitignore
- cmd/build.go
- cmd/build_test.go
- cmd/root_test.go
- launch/docker.go
- launch/launch.go
- launch/launch_test.go
add `--artifacts-dir` option described in [design doc](https://github.com/screwdriver-cd/screwdriver/blob/master/design/sd-local.md#user-content-options)
- Add options to the subcommand.
- Pass the arg to `launch` and `buildlog`
[sd-local design](https://github.com/screwdriver-cd/screwdriver/blob/master/design/sd-local.md#user-content-options)
> feat: --artifacts-dir option

- cmd/build.go
- launch/docker.go
- launch/docker_test.go
If sd-local doesn't pull image, latest image may not be actual latest. Therefore we make sd-local to pull image before run build.
- pull launcher image
- pull build image
- fix artifact dir mode
I think it is better to add option not to pull build image. It is because sometime user want to run build with local docker image. 
If it is necessary, we will add this option to sd-local design with another PR.
> fix: Always pull image

- cmd/build.go
- cmd/build_test.go
- cmd/root_test.go
- cmd/testdata/test_env
- go.mod
- go.sum
- launch/launch.go
- launch/launch_test.go
This PR makes `sd-local` enable to set environment variables.
- Add `--env` and `--env-file` options.
- When both `--env` and `--env-file` options are used, we give priority to `--env` about environment variables used in both options.
> feat(1314): Add env option

- .goreleaser.yml
- screwdriver.yaml
To install sd-local, we have to use `go get`, but it's a littel hard to use for users who aren't familiar with go.
This PR publish the binary of sd-local to github release.
> feat(1314): add publish job to release

- .gitignore
release step was failed because of `git is currently in a dirty state`
https://cd.screwdriver.cd/pipelines/4014/builds/174135/steps/release
- ignore `./VERSION` in `.gitignore` because `./VERSION` directory is created by `tag` step.
> fix: Ignore VERSION

- .goreleaser.yml
- cmd/root.go
- cmd/version.go
- cmd/version_test.go
This command is expected to keep updating, so I thought it would be better for users to know the version.
I added `version` subcommand.
The version is embedded when building.
> Enable to display current command's version

- cmd/build.go
- cmd/build_test.go
- cmd/root_test.go
- launch/docker.go
- launch/docker_test.go
- launch/launch.go
Executing `sd-local build <job>` by a no-privileged user will fail by permission problems on the container runtime.
So, now they should use `sudo sd-local` and it causes to make `sd-artifacts` directory in the current directory by `root`.
Therefore this PR add `--sudo` option for executing the container runtime to avoid problems above.
- add `--sudo` option
- If it is used, `sd-local` execute `docker` with `sudo` command.
screwdriver-cd/screwdriver#1314
https://github.com/screwdriver-cd/screwdriver/blob/master/design/sd-local.md#options
(After this PR is merged, we will fix the design doc.)
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on …
> feat(1314): Add --sudo option 

- launch/launch.go
- launch/launch_test.go
users cannot use `sd-cmd` with `sd-local`
```
$ sd-local build --src-url https://github.com/screwdriver-cd-test/command-example.git main
INFO[0000] Pulling the source code from https://github.com/screwdriver-cd-test/command-example.git...
INFO[0002] Prepare to start build...
sd-setup-launcher: Screwdriver Launcher information
sd-setup-launcher: Version:        v6.0.48
sd-setup-launcher: Pipeline:       #0
sd-setup-launcher: Job:            main
sd-setup-launcher: Build:          #0
sd-setup-launcher: Workspace Dir:  /sd/workspace
sd-setup-launcher: Checkout Dir:     /sd/workspace/src/screwdriver.cd/sd-local/local-build
sd-setup-launcher: Source Dir:     /sd/workspace/src/screwdriver.cd/sd-local/local-build
sd-setup-launcher: Artifacts Dir:  /sd/workspace/artifacts
validate: $ sd-cmd …
```
> fix: add version to env url

- cmd/build.go
- cmd/build_test.go
- cmd/root_test.go
- cmd/testdata/config
Add `--local` option to build command to use config file in current directory.
Add `--local` option.
https://github.com/screwdriver-cd/screwdriver/issues/1314
https://github.com/screwdriver-cd/screwdriver/blob/master/design/sd-local.md#options
(After this PR is merged, we will fix the design doc.)
> feat(1314): Add --local option to build command

- cmd/build.go
- cmd/root.go
- cmd/root_test.go
- launch/docker.go
- launch/docker_test.go
- launch/launch.go
- launch/launch_test.go
- scm/scm.go
- scm/scm_test.go
When "sd-local" completed or interrupted, the Docker volume, processes, etc. were not deleted and were not clean.
Fixed to remove Docker volume, processes, etc.
Added the following to the process:
- When interrupted:
- It kills the process that was running.
- Delete the docker volume
- Delete the repository when using the `--src-url` option.
- When the execution is complete:
- Delete the docker volume
- Delete the repository when using the `--src-url` option.
> feat: Cleanup process after execution

- cmd/root.go
- sd-local.go
The following two bugs were found
- The exit status is set to 1 even if it is a normal exit.
- Some error messages are not displayed at the end of the error.
- Separated `os.Exit` from `clean` function.
- Use `logrus` to display errors in sd-local.go.
> Fix exit status and error message bug

- cmd/build.go
- cmd/build_test.go
- cmd/config/config.go
- cmd/config/create.go
- cmd/config/create_test.go
- cmd/config/set.go
- cmd/config/view.go
- cmd/config/view_test.go
- cmd/root_test.go
- config/config.go
- config/config_test.go
- launch/docker.go
- launch/docker_test.go
- launch/launch.go
- launch/launch_test.go
We are reconsidering sd-local config scheme.
This PR makes sd-local enable to use the new config scheme.
- Implement `config create` subcommand to create the new config
- Refactor `config` package and `cmd/config` package
- Remove `--local` option in `cmd/config`
https://github.com/screwdriver-cd/screwdriver/issues/2050
> fix(2050): Implement create subcommand for config

- cmd/config/config.go
- cmd/config/delete.go
- cmd/config/delete_test.go
- cmd/config/testdata/config
- config/config.go
- config/config_test.go
- config/testdata/emptyConfigs
We are reconsidering sd-local config scheme.
This PR makes sd-local enable to use the new config scheme.
- Implement `config delete` subcommand to delete a config
https://github.com/screwdriver-cd/screwdriver/issues/2050
> fix(2050): Implement delete subcommand for config

- cmd/config/testdata/config_no_current
- cmd/config/testdata/local_config
- cmd/config/view.go
- cmd/config/view_test.go
We are now re-considering local config and implementing new config scheme.
This PR makes `sd-local config view` adapts new config scheme as shows in https://github.com/screwdriver-cd/screwdriver/issues/2050#issuecomment-609675304
- Fix config view appearance
- Delete `cmd/config/testdata/local_config`
screwdriver-cd/screwdriver#2050
> fix(2050): fix config view for new config scheme

- README.md
- cmd/build.go
- cmd/build_test.go
- cmd/config/config.go
- cmd/root_test.go
`local` option is no longer needed because we created new config command for multiple configs.
This dropped `local` option.
https://github.com/screwdriver-cd/screwdriver/issues/2050
> fix(2050): remove local option

- README.md
- cmd/build.go
- cmd/root.go
- cmd/root_test.go
- launch/docker.go
- launch/docker_test.go
- launch/launch.go
If it takes a long time with `docker pull` etc., it is not display logs for a long time and cannot be understood the progress.
Fix to display the progress of `docker pull` etc with `--verbose` option.
> fix: add execDockerCommand logs

- buildlog/buildlog.go
- buildlog/buildlog_test.go
- cmd/build.go
- cmd/root_test.go
Remove the sleep process in `cmd/build.go`.
Because `logger.Run()` is a sub goroutine, main goroutine must wait until all `builds.log` has been read after the call of `logger.Stop()`.
We make logger have a channel to notify the end of both build and tail process of `builds.log`, so that main goroutine doesn't sleep by waiting for the channel.
- Remove `time.Sleep` in `cmd/build.go`
- Add `loggerDone` field to log struct
- `log.output()` returns a bool value indicating whether EOF was read or not
> Remove the sleep process in build command

- buildlog/buildlog.go
- buildlog/buildlog_test.go
sd-local caused Error when build logs is too long line (over 4096 bytes).
This PR makes sd-local enable to output too long log line.
> fix: support too long buildlogs

- buildlog/buildlog.go
- buildlog/buildlog_test.go
sd-local will stop logging when parse error happen.
We fixed the problem above. If the parse error happens, show warning message and logging will continue.
> fix: skip parse error

- cmd/update.go
- cmd/update_test.go
FIX: https://github.com/screwdriver-cd/sd-local/pull/42
When I run the update command, show following error.
```
ERROR  [0000] This is a development version and cannot be updated
```
This error is caused by the scope of `currentVersion.`
The problem occurs when building use golang version 1.13.
This PR changes the order of processing so that currentVersion is enabled.
The following error message is incorrect.
```
ERROR  [0000] Current version is latest
```
Modify it  a warning message.
related
- https://github.com/screwdriver-cd/sd-local/pull/42
- https://github.com/screwdriver-cd/guide/pull/416
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this …
> fix: sd-local update command

- Makefile
- buildlog/buildlog.go
If lint fails, the build doesn't fail.
I fixed it so that if the lint fails, the build fails too.
> fix: Set exit status by lint

- Makefile
- screwdriver.yaml
I often forget to run the `go mod tidy` command.
So I added the `go mod tidy` command to the test job so that I can also run it with the make command.
- add `go mod tidy` command in test job
- add `go mod tidy` command in Makefile
> Add go mod tidy command

- launch/interact.go
The interactive mode is a new feature in the following PRs
https://github.com/screwdriver-cd/sd-local/pull/45
If the step is large, interactive mode will not work.
https://github.com/screwdriver-cd/screwdriver/issues/2238#issuecomment-724857296
This problem occurs when the size of the command to be sent exceeds the size of `/dev/pts`.
Example.
With ibu1224's mac book pro environment, it's only `1kb`.
Therefore, I will fix it to work properly
Determine the maximum number of bytes that can be sent to `/dev/pts`.
If the maximum number you can write to `/dev/pts` is less than this value, need to fix it.
If you have any other good ideas, please let me know.
https://man7.org/linux/man-pages/man4/pts.4.html
https://github.com/screwdriver-cd/screwdriver/issues/2238
I confirm that this …
> fix(2238): add limit writing to /dev/pts

- README.md
- cmd/build.go
- cmd/build_test.go
- cmd/root_test.go
- launch/docker.go
- launch/docker_test.go
- launch/launch.go
fix https://github.com/screwdriver-cd/screwdriver/issues/2274
Since macOS sockets do not seem to be available on the docker container, ~I decided to mount the ssh key~ instead we can use `/run/host-services/ssh-auth.sock` as the socket. On the linux machine connected with agent forwarding enabled, mounting `$SSH_AUTH_SOCK` solves the problem.
https://github.com/screwdriver-cd/screwdriver/issues/2274
https://screwdriver-cd.slack.com/archives/C1T5T67PT/p1605035781056600
https://stackoverflow.com/questions/27036936/using-ssh-agent-with-docker-on-macos
> fix(2274): pass ssh agent to build container

- launch/docker.go
`sd-local` is failing with error 
```
INFO   [0002] $ docker container run --rm -v SD_LAUNCH_BIN:/opt/sd/ -v SD_LAUNCH_HAB:/hab  screwdrivercd/launcher:latest --entrypoint /bin/echo set up bin
INFO   [0003] sudo available in Container?
root
Symlink hab cache
Tue Dec  1 22:39:07 UTC 2020
Failed to create /hab/pkgs/core/*
Failed to symlink hab cache
Creating workspace and log pipe
Tue Dec  1 22:39:07 UTC 2020
Waiting for log pipe to be ready
Tue Dec  1 22:39:07 UTC 2020
Symlink hab cache, log pipe is ready
Tue Dec  1 22:39:07 UTC 2020
find: /opt/sd/hab/pkgs/core: No such file or directory
find: /opt/sd/hab/pkgs/core: No such file or directory
/bin/bash: --: invalid option
Usage:	/bin/bash [GNU long option] [option] ...
/bin/bash [GNU long option] [option] script-file ...
GNU long options: …
```
> fix: entry point order

- launch/docker.go
fix https://github.com/screwdriver-cd/screwdriver/issues/2280
This PR enables envs which include spaces in sd-local's interactive mode.
```
sd-local# echo $MY_MSG
this is test
```
https://github.com/screwdriver-cd/screwdriver/issues/2280
> fix(2280): Envs which include spaces become blank in interactive mode

- cmd/build.go
- cmd/build_test.go
- cmd/root_test.go
- launch/docker.go
- launch/docker_test.go
- launch/launch.go
RHEL8 greatly prefers podman over docker; podman-docker is a shim that has slightly different flags
- Determine whether dockerIsPodman by running `docker --version` and looking for "podman".
- Fix the volume creation to not pass the `--name` flag when dockerIsPodman
> Add podman support by omitting the --name arg from volume creation.

- cmd/build.go
- cmd/build_test.go
- cmd/root_test.go
- launch/docker.go
- launch/docker_test.go
- launch/launch.go
* Both podman-docker and docker will create volumes that don't exist when first mentioned and honor VOLUME declarations by copying the layer's content to the mounted location for volumes that don't exist.
* Docker also allows noticing "first-mount" of pre-created volumes, but podman doesn't.
So, to find common ground and revert logic created in #59 this PR stops pre-creating the volumes so that it works for both docker and podman-docker
> Both Docker and Podman populate non-existent VOLUMES on first mention; stop pre-creating them

- cmd/build_test.go
- cmd/root_test.go
- launch/docker_test.go
Fix the following issue
https://github.com/screwdriver-cd/screwdriver/issues/2352
`SSH_AUTH_SOCK` is dependent on the environment in which it is run.
So, get the `SSH_AUTH_SOCK` of the execution environment and run the test.
Also, add the case when `SSH_AUTH_SOCK` is not set and it works
issue: https://github.com/screwdriver-cd/screwdriver/issues/2352
> fix(2352): sd-local tests won't work in mac

- cmd/config/set.go
- cmd/config/set_test.go
If the wrong key is set, the exit code will be zero.
```
$ sd-local config set invalid-key invalid-value
Set the config of sd-local.
Can set the below settings:
* Screwdriver.cd API URL as "api-url"
* Screwdriver.cd Store URL as "store-url"
* Screwdriver.cd Token as "token"
* Screwdriver.cd launcher version as "launcher-version"
* Screwdriver.cd UUID as "UUID"
* Screwdriver.cd launcher image as "launcher-image"
Usage:
sd-local config set [key] [value] [flags]
Flags:
-h, --help   help for set
Global Flags:
$ echo $?
0
```
Since it is an error, a non-zero value should be returned.
* Refactoring test code (https://github.com/screwdriver-cd/sd-local/commit/826704e1aba3b1d1b0c1abee8562aabb26018b52)
* Add a test case (https://github.com/screwdriver-cd/sd-local/pull/70/commits/a567a60eca0b0df8576 …
> Fix an error handling for `config set` command

- launch/docker.go
- launch/interact.go
The interactive mode of sd-local has a lot of logs of the setup process, which is unnecessary for the user, and it is difficult to know that the startup is completed.
The log of the setup process will hidden.
If the verbose option is set true, the behavior remains the same.
https://en.wikipedia.org/wiki/ANSI_escape_code
> fix: hide logs in interactive mode

- README.md
For requests of https://github.com/screwdriver-cd/sd-local/pull/74#issuecomment-951476434.
I added evalation order of environment variable for a build to README.
https://github.com/screwdriver-cd/sd-local/pull/74
> docs: add evalation order of env to readme

- README.md
- cmd/build.go
- cmd/root_test.go
- launch/docker.go
- launch/docker_test.go
- launch/launch.go
https://github.com/screwdriver-cd/screwdriver/issues/2645
Support `-u` flag to pass a custom container user.
```
❯ ./sd-local build test -i
INFO   [0000] Prepare to start build...
INFO   [0028] Pulling docker image from golang:1.17.2...
please wait while sd-local setup process...
...
Welcome to sd-local interactive mode. To exit type 'exit'
sd-local# whoami
root
```
```
❯ ./sd-local build test -i -u nobody
INFO   [0001] Prepare to start build...
INFO   [0009] Pulling docker image from golang:1.17.2...
please wait while sd-local setup process...
.......
sd-local#whoami
nobody
sd-local#
```
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on …
> feat: support passing custom build user

- .goreleaser.yml
`sd-local` would be used on macOS. And latest Mac computers an ARM-based.
- add binary for arm64 arch
- add universal binary for macOS with amd64 and arm64
- [macOS Universal Binaries - GoReleaser](https://goreleaser.com/customization/universalbinaries/)
- https://github.com/screwdriver-cd/screwdriver/issues/2692
> feat(2692): add arm64 and universal binary

- screwdriver.yaml
go version is pinned.
use latest patch version of golang 1.17.
> fix: use latest patch version of golang 1.17

- launch/docker.go
- launch/docker_test.go
This PR solves the following issue.
sd-local does not work properly when using a Docker image with entrypoint specified.
This problem fails to start successfully when in interactive mode and
When run normally, the process will terminate without executing the user step.
Here is the Dockerfile where the problem occurs.
`Dockerfile`
```
FROM node:16
ENTRYPOINT ["/bin/echo", "'TEST'"]
```
This problem occurs only with sd-local,  not with screwdriver builds.
Set up the build so that entrypoint is assigned to /bin/sh at the start of the build.
> fix: work with images that specify an entrypoint

- README.md
- launch/docker.go
- launch/docker_test.go
- launch/launch.go
- launch/launch_test.go
- screwdriver/screwdriver.go
I want to be able to debug builds locally using docker commands.
Add the feature to start the `dind-rootless` container if `screwdriver.cd/dockerEnabled: true` is set in the annotation of the job.
https://github.com/screwdriver-cd/screwdriver/issues/2969
> feat(2969): Make docker commands available in the build

- launch/docker.go
- launch/docker_test.go
- launch/launch.go
Even when Dind is not used, it is still trying to clear the Dind image and generates a warning.
We fix so that when Dind is not used, the process of clearing the Dind image is not performed.
https://github.com/screwdriver-cd/screwdriver/issues/2969
> fix(2969): Do not clear DinD images when DinD is not used

- buildlog/buildlog_test.go
- cmd/build.go
- cmd/build_test.go
- config/config_test.go
- screwdriver/screwdriver.go
PR replaces the deprecated usage of the `io/ioutil` package.  
Modernise the Go code of the repository.
https://github.com/golang/go/issues/42025
https://github.com/golang/go/issues/40026
https://github.com/screwdriver-cd/screwdriver/issues/2983
> fix(2983): replace deprecated usages of io/ioutil pkg

- .goreleaser.yml
- README.md
- cmd/build.go
- cmd/build_test.go
- cmd/root_test.go
- launch/docker.go
- launch/docker_test.go
- launch/launch.go
- launch/launch_test.go
- screwdriver/screwdriver_test.go
We can debug build in interactive mode, but executing commands of steps is a little difficult.
We need to copy and paste to run commands of each steps.
Create utils to execute step commands in interactive mode.
e.g.
```bash
$ sd-local build -i test
sd-local# sdrun <step name>
foo
```
Utils are created in local `.sd-utils` directory and this directory is mounted on `/sd/workspace/sd-utils` in build container.
Issues
- https://github.com/screwdriver-cd/sd-local/issues/72
> feat(72): Make it easy to execute commands in steps

- launch/docker.go
fix (https://github.com/screwdriver-cd/sd-local/pull/96)
When writing a step file, a single-line step does not have a line break at the end, so when the step is executed, the execution result is displayed starting from the continuation of the step contents.
fix the results of a single-line step execution to be displayed starting with a new line.
https://github.com/screwdriver-cd/sd-local/issues/72
https://github.com/screwdriver-cd/sd-local/pull/96
> feat(72): fix to output step file in interactive mode
